/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pertemuan_enam;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo IP 330-14IKB
 */
public class Delete extends javax.swing.JFrame {

    private EntityManagerFactory emf;
    private EntityManager em;
    private String idBukuToDelete;
    private String kode;
    private String nama;

    /**
     * Creates new form Delete
     */
    public Delete() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Konfirmasi Hapus Data");
    }

    public Delete(String idBuku) {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Konfirmasi Hapus Data");
        this.idBukuToDelete = idBuku;
        this.nama = "";

        jLabel1.setText("Apakah anda yakin ingin menghapus data dengan ID: " + idBuku + "?");
    }

    Delete(String kode, String nama) {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Konfirmasi Hapus Data");
        this.idBukuToDelete = kode;
        this.nama = nama;

        jLabel1.setText("Apakah anda yakin ingin menghapus data: " + kode + " - " + nama + "?");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Yes_Button_Delete = new javax.swing.JButton();
        No_Button_Delete = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        jLabel1.setText("Apakah anda yakin ingin menghapus data ini?!");

        Yes_Button_Delete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Yes_Button_Delete.setText("YES");
        Yes_Button_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Yes_Button_DeleteActionPerformed(evt);
            }
        });

        No_Button_Delete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        No_Button_Delete.setText("NO");
        No_Button_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                No_Button_DeleteActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jLabel4.setText("KONFIRMASI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(Yes_Button_Delete)
                        .addGap(47, 47, 47)
                        .addComponent(No_Button_Delete))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel4)))
                .addContainerGap(121, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Yes_Button_Delete)
                    .addComponent(No_Button_Delete))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Yes_Button_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Yes_Button_DeleteActionPerformed
        // TODO add your handling code here:
        deleteData();
    }//GEN-LAST:event_Yes_Button_DeleteActionPerformed

    private void No_Button_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_No_Button_DeleteActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_No_Button_DeleteActionPerformed

    private void deleteData() {
        if (idBukuToDelete == null || idBukuToDelete.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "ID buku tidak valid!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            dispose();
            return;
        }

        emf = null;
        em = null;

        try {
            emf = Persistence.createEntityManagerFactory("Pertemuan_EnamPU");
            em = emf.createEntityManager();

            em.getTransaction().begin();

            // Cari dan hapus data menggunakan JPA
            Buku buku = em.find(Buku.class, idBukuToDelete.trim());

            if (buku != null) {
                em.remove(buku);
                em.getTransaction().commit();

                JOptionPane.showMessageDialog(this,
                        "Data berhasil dihapus!",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                em.getTransaction().rollback();
                JOptionPane.showMessageDialog(this,
                        "Data tidak ditemukan! Mungkin sudah dihapus sebelumnya.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }

            dispose();

        } catch (Exception ex) {
            // Rollback jika ada error
            if (em != null && em.getTransaction().isActive()) {
                em.getTransaction().rollback();
            }
            JOptionPane.showMessageDialog(this,
                    "Error: " + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        } finally {
            // Clean up resources
            if (em != null && em.isOpen()) {
                em.close();
            }
            if (emf != null && emf.isOpen()) {
                emf.close();
            }
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton No_Button_Delete;
    private javax.swing.JButton Yes_Button_Delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
