/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pertemuan_enam;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo IP 330-14IKB
 */
public class NewJFrame extends javax.swing.JFrame {

    private Koneksi koneksi;
    private EntityManagerFactory emf;
    private EntityManager em;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        koneksi = new Koneksi();
        setLocationRelativeTo(null);
        setTitle("Data Buku Perpustakaan");
        loadDataFromDatabase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btn_Insert = new javax.swing.JButton();
        btn_Update = new javax.swing.JButton();
        btn_Delete = new javax.swing.JButton();
        btn_Cetak = new javax.swing.JButton();
        btn_Upload = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Buku", "Judul", "Penulis", "Penerbit", "Tahun"
            }
        ));
        jScrollPane1.setViewportView(Table);

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel1.setText("DATA BUKU PERPUSTAKAAN");

        btn_Insert.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Insert.setText("INSERT");
        btn_Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InsertActionPerformed(evt);
            }
        });

        btn_Update.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Update.setText("UPDATE");
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });

        btn_Delete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Delete.setText("DELETE");
        btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteActionPerformed(evt);
            }
        });

        btn_Cetak.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Cetak.setText("CETAK");
        btn_Cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CetakActionPerformed(evt);
            }
        });

        btn_Upload.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Upload.setText("UPLOAD");
        btn_Upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UploadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(btn_Insert)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Update)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Delete)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Cetak)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Upload))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Insert)
                    .addComponent(btn_Update)
                    .addComponent(btn_Delete)
                    .addComponent(btn_Cetak)
                    .addComponent(btn_Upload))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InsertActionPerformed
        // TODO add your handling code here:
        try {
            Insert insertDialog = new Insert();
            insertDialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosed(java.awt.event.WindowEvent e) {
                    loadDataFromDatabase();
                }
            });
            insertDialog.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_InsertActionPerformed

    private void btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = Table.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang akan dihapus!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String kode = Table.getValueAt(selectedRow, 0).toString();
        String nama = Table.getValueAt(selectedRow, 1).toString();

        int confirm1 = JOptionPane.showConfirmDialog(
                this,
                "Yakin ingin menghapus data:\n" + kode + " - " + nama + "?",
                "Konfirmasi Hapus",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm1 == JOptionPane.YES_OPTION) {
            Delete deleteDialog = new Delete(kode, nama);
            deleteDialog.setLocationRelativeTo(this);
            deleteDialog.setVisible(true);

            deleteDialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosed(java.awt.event.WindowEvent e) {
                    loadDataFromDatabase();
                }
            });
        }
    }//GEN-LAST:event_btn_DeleteActionPerformed

    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
        // TODO add your handling code here:
        int selectedRow = Table.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                    "Pilih data yang akan diupdate terlebih dahulu!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String idBuku = Table.getValueAt(selectedRow, 0).toString();
        Update updateDialog = new Update(idBuku);
        updateDialog.setVisible(true);

        updateDialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                loadDataFromDatabase();
            }
        });
    }//GEN-LAST:event_btn_UpdateActionPerformed

    private void btn_CetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CetakActionPerformed
        // TODO add your handling code here:
        try {

            cetakDenganJasper();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error: " + e.getMessage() + "\nPastikan library JasperReports sudah ditambahkan!",
                    "Error Cetak",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    private void cetakDenganJasper() {
        Connection conn = null;
        try {

            conn = koneksi.getConnection();

            String[] possiblePaths = {
                "report4.jasper",
                "src/pertemuan_enam/report4.jasper",
                "./src/pertemuan_enam/report4.jasper"
            };

            String reportPath = null;
            for (String path : possiblePaths) {
                java.io.File file = new java.io.File(path);
                if (file.exists()) {
                    reportPath = path;
                    break;
                }
            }

            if (reportPath == null) {
                JOptionPane.showMessageDialog(this,
                        "File report4.jasper tidak ditemukan!\nPastikan file ada di folder yang benar.",
                        "File Tidak Ditemukan",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            java.util.Map<String, Object> parameters = new java.util.HashMap<>();
            parameters.put("JudulLaporan", "DATA BUKU PERPUSTAKAAN");
            parameters.put("TanggalCetak", new java.util.Date());

            net.sf.jasperreports.engine.JasperPrint jasperPrint
                    = net.sf.jasperreports.engine.JasperFillManager.fillReport(reportPath, parameters, conn);

            net.sf.jasperreports.view.JasperViewer viewer
                    = new net.sf.jasperreports.view.JasperViewer(jasperPrint, false);
            viewer.setTitle("Laporan Data Buku");
            viewer.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error saat mencetak: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } finally {
            // Tutup koneksi
            if (conn != null) {
                try {
                    conn.close();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_btn_CetakActionPerformed

    private void btn_UploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UploadActionPerformed
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        int returnValue = jfc.showOpenDialog(null);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File filePilihan = jfc.getSelectedFile();
            System.out.println("yang dipilih : " + filePilihan.getAbsolutePath());

            // === DIUBAH: KEMBALI PAKAI JPA UNTUK UPLOAD ===
            EntityManagerFactory emf = null;
            EntityManager em = null;

            try (BufferedReader br = new BufferedReader(new FileReader(filePilihan))) {
                emf = Persistence.createEntityManagerFactory("Pertemuan_EnamPU");
                em = emf.createEntityManager();

                String baris;
                String pemisah = ";";
                int successCount = 0;
                int errorCount = 0;

                while ((baris = br.readLine()) != null) {
                    String[] data = baris.split(pemisah);

                    if (data.length >= 5) {
                        String id_buku = data[0];
                        String judul = data[1];
                        String penulis = data[2];
                        String penerbit = data[3];
                        String tahunStr = data[4];

                        if (!id_buku.isEmpty() && !judul.isEmpty() && !penulis.isEmpty() && !penerbit.isEmpty() && !tahunStr.isEmpty()) {
                            try {
                                int tahun = Integer.parseInt(tahunStr.trim());

                                // Buat object Buku
                                Buku buku = new Buku();
                                buku.setIdBuku(id_buku);
                                buku.setJudul(judul);
                                buku.setPenulis(penulis);
                                buku.setPenerbit(penerbit);
                                buku.setTahun(tahun);

                                // Simpan dengan JPA
                                em.getTransaction().begin();
                                em.persist(buku);
                                em.getTransaction().commit();

                                successCount++;

                            } catch (Exception ex) {
                                // Rollback transaction untuk baris ini
                                if (em.getTransaction().isActive()) {
                                    em.getTransaction().rollback();
                                }
                                errorCount++;
                                System.out.println("Error pada baris: " + baris + " - " + ex.getMessage());
                            }
                        }
                    }
                }

                String message = successCount + " data berhasil diupload dari CSV!";
                if (errorCount > 0) {
                    message += "\n" + errorCount + " data gagal diupload.";
                }

                JOptionPane.showMessageDialog(this, message, "Upload Result", JOptionPane.INFORMATION_MESSAGE);
                loadDataFromDatabase(); // Refresh tabel

            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "File tidak ditemukan: " + ex.getMessage());
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error membaca file: " + ex.getMessage());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
            } finally {
                if (em != null && em.isOpen()) {
                    em.close();
                }
                if (emf != null && emf.isOpen()) {
                    emf.close();
                }
            }
        }
    }//GEN-LAST:event_btn_UploadActionPerformed

    private void loadDataFromDatabase() {
        // COBA JPA DULU, JIKA GAGAL PAKAI JDBC
        if (tryLoadDataWithJPA()) {
            System.out.println("✓ Data loaded with JPA");
        } else {
            // Fallback ke JDBC
            System.out.println("⚠ Falling back to JDBC");
            loadDataWithJDBC();
        }
    }

    private boolean tryLoadDataWithJPA() {
        EntityManagerFactory emf = null;
        EntityManager em = null;

        try {
            emf = Persistence.createEntityManagerFactory("Pertemuan_EnamPU");
            em = emf.createEntityManager();

            // Method 1: Coba Native Query dulu (lebih reliable)
            try {
                List<Buku> listBuku = em.createNativeQuery(
                        "SELECT * FROM buku ORDER BY id_buku", Buku.class).getResultList();
                populateTable(listBuku);
                return true;
            } catch (Exception e1) {
                System.out.println("Native query failed: " + e1.getMessage());

                // Method 2: Coba JPQL dengan fully qualified name
                try {
                    List<Buku> listBuku = em.createQuery(
                            "SELECT b FROM pertemuan_enam.Buku b ORDER BY b.idBuku", Buku.class).getResultList();
                    populateTable(listBuku);
                    return true;
                } catch (Exception e2) {
                    System.out.println("JPQL failed: " + e2.getMessage());
                    return false;
                }
            }

        } catch (Exception ex) {
            System.out.println("JPA initialization failed: " + ex.getMessage());
            return false;
        } finally {
            if (em != null && em.isOpen()) {
                em.close();
            }
            if (emf != null && emf.isOpen()) {
                emf.close();
            }
        }
    }

    private void populateTable(List<Buku> listBuku) {
        DefaultTableModel model = (DefaultTableModel) Table.getModel();
        model.setRowCount(0);

        for (Buku buku : listBuku) {
            model.addRow(new Object[]{
                buku.getIdBuku(),
                buku.getJudul(),
                buku.getPenulis(),
                buku.getPenerbit(),
                buku.getTahun()
            });
        }
    }

    private void loadDataWithJDBC() {
        try {
            Connection conn = koneksi.getConnection();
            String sql = "SELECT * FROM buku ORDER BY id_buku";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();

            DefaultTableModel model = (DefaultTableModel) Table.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_buku"),
                    rs.getString("judul"),
                    rs.getString("penulis"),
                    rs.getString("penerbit"),
                    rs.getInt("tahun")
                });
            }

            rs.close();
            pstmt.close();
            conn.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                    "JDBC Error: " + ex.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JButton btn_Cetak;
    private javax.swing.JButton btn_Delete;
    private javax.swing.JButton btn_Insert;
    private javax.swing.JButton btn_Update;
    private javax.swing.JButton btn_Upload;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
